%<*includetag>

\section{Assignment 4}
\subsection{Selection and building nominal features}
In our dataset we have several binary features, such as weekdays (\texttt{weekday\_is\_monday}, \texttt{weekday\_is\_tuesday} and so on) and  belonging to one of the channels (\texttt{data\_channel\_is\_lifestyle}, \texttt{data\_channel\_is\_entertainment} and so on). Therefore we built two nominal features:
\begin{itemize}
\item channel: integer values ranging between 0 and 6 ('No channel', 'Lifestyle', 'Entertainment', 'Business', 'Social Media', 'Tech', 'World')
\item weekday: integer values ranging between 1 and 7 
\end{itemize}

To obtain the third nominal feature we divide the feature \texttt{timedelta} into four parts : days between the article publication and the dataset acquisition.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}  
\hlstd{timegroup} \hlkwb{<-} \hlkwa{cut}\hlstd{(data$timedelta, breaks = 4})
\end{alltt}
\end{kframe}
\end{knitrout} 

And we break range of values of \texttt{timedelta} into intervals of approximate equal size: $(7.28,189]$, $(189,370]$, $(370,550]$, $(550,732]$. 

\subsection{Contingency tables over features}
Conditional cross-classification talbes between introduced nominal fetures are obtained with R-function \texttt{table} as is shown below. Results are presented in Tables \ref{tbl:cont_table_ch_timed} -- \ref{tbl:cont_table_week_timegroup}. 
Simple analysis of the aforementioned tables reveals that there aren't any conceptual associations between categories. So our analisys could go deeper and discover some hidden dependencies with techinques that were explained in lectures.



\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}  
table(data$channel, data$timegroup)
table(data$channel, data$weekday)
\end{alltt}
\end{kframe}
\end{knitrout} 

\begin{table}[h]
\begin{center}
\small
\begin{minipage}[h]{0.45\linewidth}
\caption{Cross classification of the \texttt{channel} with \texttt{timegroup}} \label{tbl:cont_table_ch_timed}
\begin{tabular}{|c|c|c|c|c|} 
 \hline
  &(7.28,189] &(189,370]& (370,550] &(550,732] \\ \hline
  0  &      412   &    327   &    361   &    381 \\ \hline
  1  &      120   &     93   &    130   &    183 \\ \hline
  2  &      573   &    473   &    341   &    348 \\ \hline
  3  &      392   &    408   &    410   &    446 \\ \hline
  4  &       81   &    154   &    163   &    192 \\ \hline
  5  &      401   &    469   &    491   &    492 \\ \hline
  6  &      901   &    564   &    373   &    321 \\ \hline
\end{tabular}
\end{minipage}
\hfill 
\begin{minipage}[h]{0.45\linewidth}
\caption{Cross classification of the \texttt{channel} with \texttt{weekday}} \label{tbl:cont_table_ch_week}
\begin{tabular}{|c|c|c|c|c|c|c|c|} 
 \hline
     &1 & 2 & 3 & 4 & 5 & 6 & 7 \\ \hline
  0  & 224 & 256 &253 &257 &238 &112 &141 \\ \hline
  1  & 80 & 95 &  92 & 85  &69  &46  &59 \\ \hline
  2  & 317 & 332 & 311 & 287 & 241 & 95 & 152 \\ \hline
  3  & 277 & 293 & 371 & 319 & 245 & 57 & 94 \\ \hline
  4  & 88 & 116 &105& 115 & 88 & 44 & 34 \\ \hline
  5  & 316 & 372 & 358 & 344 & 244 & 125 & 94\\ \hline
  6  & 360& 379& 399& 392& 342& 136& 151 \\ \hline
\end{tabular}
\end{minipage}
\end{center}
\end{table}


\begin{table}[h!]
\begin{center}
\small
\caption{Cross classification of the \texttt{weekday} with \texttt{timegroup} }
\label{tbl:cont_table_week_timegroup}
\begin{tabular}{|c|c|c|c|c|} 
\hline
& (7.28,189] &(189,370] &(370,550] &(550,732]\\ \hline
1 &         57 &       40 &       30 &       36\\ \hline
2 &         48 &       41 &       37 &       45\\ \hline
3 &         51 &       49 &       48 &       40\\ \hline
4 &         41 &       45 &       49 &       48\\ \hline
5 &         46 &       35 &       29 &       33\\ \hline
6 &         21 &       13 &       16 &       17\\ \hline
7 &         20 &       24 &       24 &       17\\ \hline
\end{tabular}
\end{center}
\end{table}







\begin{table}[h]
\begin{center}
\small
\caption{Conditional frequency table over \texttt{channel} and \texttt{timegroup}}
\label{tbl:cont_table_ch_timed_freq}
\begin{tabular}{|c|c|c|c|c|c|} 
\hline
& (7.28,189] &(189,370] &(370,550] &(550,732] &   Sum \\ \hline
0   &       4.12 &     3.27 &     3.61 &     3.81 & 14.81 \\ \hline
1   &       1.20 &     0.93 &     1.30 &     1.83 &  5.26 \\ \hline
2   &       5.73 &     4.73 &     3.41 &     3.48 & 17.35 \\ \hline
3   &       3.92 &     4.08 &     4.10 &     4.46 & 16.56 \\ \hline
4   &       0.81 &     1.54 &     1.63 &     1.92 &  5.90 \\ \hline
5   &       4.01 &     4.69 &     4.91 &     4.92 & 18.53 \\ \hline
6   &       9.01 &     5.64 &     3.73 &     3.21 & 21.59 \\ \hline
Sum &      28.80 &    24.88 &    22.69 &    23.63 &100.00 \\ \hline
\end{tabular}
\end{center}
\end{table}

\begin{table}[h]
\small
\begin{center}
\caption{Conditional frequency table over \texttt{channel} and \texttt{weekday}} 
\label{tbl:cont_table_ch_week_freq}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|} 
\hline
&    1 &     2 &     3 &     4 &     5  &    6 &     7 &   Sum \\ \hline
0   & 2.24 &  2.56 &  2.53 &  2.57 &  2.38  & 1.12 &  1.41 & 14.81 \\ \hline
1   & 0.80 &  0.95 &  0.92 &  0.85 &  0.69  & 0.46 &  0.59 &  5.26 \\ \hline
2   & 3.17 &  3.32 &  3.11 &  2.87 &  2.41  & 0.95 &  1.52 & 17.35 \\ \hline
3   & 2.77 &  2.93 &  3.71 &  3.19 &  2.45  & 0.57 &  0.94 & 16.56 \\ \hline
4   & 0.88 &  1.16 &  1.05 &  1.15 &  0.88  & 0.44 &  0.34 &  5.90 \\ \hline
5   & 3.16 &  3.72 &  3.58 &  3.44 &  2.44  & 1.25 &  0.94 & 18.53 \\ \hline
6   & 3.60 &  3.79 &  3.99 &  3.92 &  3.42  & 1.36 &  1.51 & 21.59 \\ \hline
Sum &16.62 & 18.43 & 18.89 & 17.99 & 14.67  & 6.15 &  7.25 &100.00 \\ \hline
\end{tabular}
\end{center}
\end{table}


\begin{table}[h]
\begin{center}
\small
\caption{Conditional frequency table over \texttt{weekday} with \texttt{timegroup} }
\label{tbl:cont_table_week_timegroup_freq}
\begin{tabular}{|c|c|c|c|c|c|} 
\hline
& (7.28,189] &(189,370] &(370,550] &(550,732] &   Sum \\ \hline
1   &        5.7 &      4.0 &      3.0 &      3.6 &  16.3 \\ \hline
2   &        4.8 &      4.1 &      3.7 &      4.5 &  17.1 \\ \hline
3   &        5.1 &      4.9 &      4.8 &      4.0 &  18.8 \\ \hline
4   &        4.1 &      4.5 &      4.9 &      4.8 &  18.3 \\ \hline
5   &        4.6 &      3.5 &      2.9 &      3.3 &  14.3 \\ \hline
6   &        2.1 &      1.3 &      1.6 &      1.7 &   6.7 \\ \hline
7   &        2.0 &      2.4 &      2.4 &      1.7 &   8.5 \\ \hline
Sum &       28.4 &     24.7 &     23.3 &     23.6 & 100.0 \\ \hline
\end{tabular}
\end{center}
\end{table}
 

 

As could be clearly seen, it is pretty cumbersome to make any conclusion about data which is presented without normalization. So, for the ease of interpretaion,  the same  data converted to relative frequencies by relating them to the total number of entities is presented in Tables \ref{tbl:cont_table_ch_timed_freq} -- \ref{tbl:cont_table_week_timegroup_freq}. 

We choose \texttt{channel}  as the common feature for comparison with two other features. Motivation for such choice is as follows, there is no much sense in cross-classification subgroups of time passed from the article publishing till dataset acquisition   and the day of the week it was published. This point of veiw is also supported by the Table \ref{tbl:cont_table_week_timegroup_freq}, which reveals no particular irregularities of the data, except the number of publication in a particular day of week.


% \clearpage
 

Quetelet relative index tables over our nominal fetures we obtain as a result of the following function:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{getQueteletIndex} \hlkwb{<-} \hlkwa{function}\hlstd{(}\hlkwc{v1}\hlstd{,} \hlkwc{v2}\hlstd{) \{}
  \hlstd{size} \hlkwb{<-} \hlkwd{length}\hlstd{(v1)}
  \hlstd{cont.table}  \hlkwb{<-} \hlkwd{table}\hlstd{(v1, v2)}
  \hlstd{row.sums}  \hlkwb{<-} \hlkwd{rowSums}\hlstd{(cont.table)}
  \hlstd{col.sums}  \hlkwb{<-} \hlkwd{colSums}\hlstd{(cont.table)}
  \hlstd{norm.cont.table}  \hlkwb{<-}  \hlstd{cont.table} \hlopt{/} \hlstd{size}
  \hlstd{norm.row.sums}  \hlkwb{<-} \hlstd{row.sums} \hlopt{/} \hlstd{size}
  \hlstd{norm.col.sums}  \hlkwb{<-} \hlstd{col.sums} \hlopt{/} \hlstd{size}
  \hlkwd{list}\hlstd{(}\hlkwc{QueteletIndexMatrix} \hlstd{= norm.cont.table} \hlopt{/} \hlstd{(norm.row.sums} \hlopt{%*%} \hlkwd{t}\hlstd{(norm.col.sums))} \hlopt{-} \hlnum{1}\hlstd{,}
       \hlkwc{PearsonIndexMatrix} \hlstd{= (}\hlopt{-}\hlstd{norm.row.sums}\hlopt{%*%}\hlkwd{t}\hlstd{(norm.col.sums)} \hlopt{+} \hlstd{norm.cont.table )} \hlopt{/}
                             \hlkwd{sqrt}\hlstd{(norm.row.sums}\hlopt{%*%}\hlkwd{t}\hlstd{(norm.col.sums)))}
\hlstd{\}}
\end{alltt}
\end{kframe}
\end{knitrout}

The results (in percent) are  presented in Tables \ref{tbl:quet_table_ch_timed}, \ref{tbl:quet_table_ch_week}. 
\begin{table}[h]
\footnotesize
\begin{center}
\begin{minipage}[h]{0.4\linewidth}
\caption{Quetelet relative index table over \texttt{channel} and \texttt{timegroup}} \label{tbl:quet_table_ch_timed}
\begin{tabular}{|c|c|c|c|c|} 
 \hline
  &(7.28,189] &(189,370]& (370,550] &(550,732] \\ \hline
  0&      -3.41  &  -11.26&      7.43&      8.87 \\ \hline
  1 &    -20.79  &  -28.94&      8.92&\textbf{47.23} \\ \hline
  2  &14.67 &\textbf{9.57}&    -13.38&    -15.12 \\ \hline
  3&     -17.81 &    -0.97&      9.12&     13.98 \\ \hline
  4 &    -52.33 & 4.91&\textbf{21.76}&     37.72 \\ \hline
  5  &   -24.86&      1.73&     16.78&     12.36 \\ \hline
  6&\textbf{44.90}&   5.00&    -23.86&    -37.08 \\ \hline
\end{tabular}
\end{minipage}
\hfill 
\begin{minipage}[h]{0.5\linewidth}
\caption{Quetelet relative index table over \texttt{channel} and \texttt{weekday}} \label{tbl:quet_table_ch_week}
\begin{tabular}{|c|c|c|c|c|c|c|c|} 
 \hline
     &1 & 2 & 3 & 4 & 5 & 6 & 7 \\ \hline
  0  &-9.00&  -6.21&  -9.57&  -3.54 &  9.54&  22.97&  31.32 \\ \hline
  1 & -8.49&  -2.00&  -7.41& -10.17 &-10.58&\textbf{42.20}&\textbf{54.71}\\ \hline
  2&\textbf{9.93}&   3.83&  -5.11&  -8.05 & -5.31& -10.97&  20.84 \\ \hline
  3&   0.64&  -4.00&\textbf{18.60}&   7.08 &  0.85& -44.03& -21.71 \\ \hline
  4& -10.26&   6.68&  -5.79&\textbf{8.35}&  1.67&  21.26& -20.51 \\ \hline
  5&   2.61&\textbf{8.93}&   2.28&   3.19 &-10.24&   9.69& -30.03 \\ \hline
  6&   0.33&  -4.75&  -2.17&   0.93 &\textbf{7.98}&   2.43&  -3.53 \\ \hline
\end{tabular}
\end{minipage}
\end{center}
\end{table}

As we can see from the Table \ref{tbl:quet_table_ch_timed}, \texttt{timegroup} is dependent with \texttt{channel} in some values. For example, we observe rather big Quetelet relative index between \textsf{Lifestyle channel} and \textsf{4th time-group}. \footnote{This could be explained with the hypothesis of some major classical lifestyle articles, which were written a long time before the dataset acquisition was occured. } 
In addition, we can't reject a dependence between \textsf{World channel} and \textsf{1st time-group}. It can be caused by not random sampling or by some extra-ordinary events with great response in the world.

Table \ref{tbl:quet_table_ch_week} provides us less surprising and slightly more predictable results: all channels are almost independent with weekdays except of \textsf{Lifestyle channel} and \textsf{Weekend} pair. This observation is easy to interpret: users visit Mashable at the weekend -- period when they have more free time (compared to workdays) to dedicate time to themselves.


\subsection{$\chi^2$--summary Quetelet index}

We  calculate and visualize $\chi^2$--summary according to \cite{CCODA_Mirkin}: we put Pearson's indices outside the parenthesis and it's squared value inside the parenthesis. Such presentation provides mush more information than usual $\chi^2$-statistics.

As we can see from the Table \ref{tbl:chi2_table_ch_timegroup}, the largest contribution (almost 30 relative \%) belongs to dependence between \textsf{World channel} and \textsf{1st time-group} (most recent articles). We can say that dependence is positive because the Pearson's index is positive.

In contrast, in Table \ref{tbl:chi2_table_ch_week} all values are approximately equal to each other, there is no outstanding dependencies. So, our first assumption about dependence between \textsf{Lifestyle} and \textsf{Weekend} is not justified.

\begin{table}[ht]
\centering
\begin{tabular}{|c|c|c|c|c|c|}
  \hline
 &(7.28,189] & (189,370] & (370,550] & (550,732] & Sum \\ 
  \hline
0 & -0.007 (0.00005) & -0.02161 (0.0004) & 0.01362 (0.0002) & 0.01659 (0.0003) & (0.00098) \\  \hline
1 & -0.02558 (0.0006) & -0.03310 (0.001) & 0.00975 (0.0001) & 0.05266 (0.003)  & (0.0046)  \\ \hline
2 & 0.03280 (0.001) & 0.01989 (0.0004) & -0.02655 (0.0007) & -0.03061 (0.0009) & (0.003)   \\ \hline
3 & -0.03889 (0.0015) & -0.00198 (0) & 0.01767 (0.0003) & 0.02765 (0.0008)     & (0.0026)  \\ \hline
4 & -0.06821 (0.0047) & 0.00595  (0.00004) & 0.02518 (0.0006) & 0.04453 (0.002)& (0.0073) \\ \hline
5 & -0.05743 (0.0033) & 0.00371 (0.00001) & 0.03441 (0.0012) & 0.02587 (0.0006)& (0.005)  \\ \hline
6 & 0.11197 (0.013) & 0.01158 (0.00013) & -0.05281 (0.00279) & -0.08375 (0.007)& (0.0225)  \\ \hline
Sum & (0.0237)      & (0.002)			& (0.006)			 & (0.0144)		   & (0.04624) \\ \hline
\end{tabular}
\caption{$\chi^2$--summary Quetelet index over \texttt{channel} and \texttt{timegroup}} \label{tbl:chi2_table_ch_timegroup}
\end{table}

\begin{table}[ht]
\centering
\footnotesize
\begin{tabular}{|c|c|c|c|c|c|c|c|c|}
  \hline
 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & Sum \\ 
  \hline
0 & -0.014  (0) & -0.01  (0) & -0.016  (0) & -0.006  (0) & 0.014  (0) & 0.022  (0) & 0.032  (0.001) & (0.002) \\  \hline
1 & -0.008  (0) & -0.002  (0) & -0.007  (0) & -0.01  (0) & -0.009  (0) & 0.024  (0.001) & 0.034  (0.001) & (0.002) \\  \hline
2 & 0.017  (0) & 0.007  (0) & -0.009  (0) & -0.014  (0) & -0.008  (0) & -0.011  (0) & 0.023  (0.001) & (0.001) \\  \hline
3 & 0.001  (0) & -0.007  (0) & 0.033  (0.001) & 0.012  (0) & 0.001  (0) & -0.044  (0.002) & -0.024  (0.001) & (0.004) \\  \hline
4 & -0.01  (0) & 0.007  (0) & -0.006  (0) & 0.009  (0) & 0.002  (0) & 0.013  (0) & -0.013  (0) & (0.001) \\  \hline
5 & 0.005  (0) & 0.017  (0) & 0.004  (0) & 0.006  (0) & -0.017  (0) & 0.01  (0) & -0.035  (0.001) & (0.002) \\  \hline
6 & 0.001  (0) & -0.009  (0) & -0.004  (0) & 0.002  (0) & 0.014  (0) & 0.003  (0) & -0.004  (0) & (0) \\  \hline
Sum & (0.001) & (0.001) & (0.002) & (0.001) & (0.001) & (0.003) & (0.005) &  (0.0124)\\ 
   \hline
\end{tabular}
\caption{$\chi^2$--summary Quetelet index over \texttt{channel} and \texttt{weekday}} \label{tbl:chi2_table_ch_week}
\end{table}

\subsection{Sufficient sample size for result to be significant}

Supposing the probabilities $p_{i+}$, $p_{+j}$, $p_{ij}$ are constant and sample size $n$ is being varied, we can get $\chi^2$-statistics from
\begin{gather*}
nX^2 = \sum\limits_{k=1}^K \sum\limits_{l=1}^L \frac{(p_{kl} - p_{k+}p_{+l})^2}{p_{k+}p_{+l}} \overset{n \to \infty}{\Rightarrow} \chi^2((K-1)(L-1))
\end{gather*} 

We know $X^2$ and $K,L$ for pairs \texttt{channel}--\texttt{timegroup} and \texttt{channel}--\texttt{weekday}, so, we can pick up $n$ so great to make $ \chi^2 $ become significantly great.


For the pair \texttt{channel}--\texttt{timegroup} and confidence level $0.95$ we have the following equation:
\begin{gather*}
n \cdot 0.04624 = \left(\chi^2_{(K-1)(L-1)}\right)^{-1} (0.95) = \left(\chi^2_{6 \cdot 3}\right)^{-1} (0.95) = 28.8693 \\
n_{0.95} \approx 625
\end{gather*}
By similar arguments we obtain sufficient number of observation for confidence level $0.99$:
\begin{gather*}
n \cdot 0.04624 = \left(\chi^2_{(K-1)(L-1)}\right)^{-1} (0.99) = \left(\chi^2_{6 \cdot 3}\right)^{-1} (0.99) = 34.80531 \\
n_{0.99} \approx 753
\end{gather*}

For the second pair \texttt{channel}--\texttt{weekday} we know $K = 7, L=7$. As in the previous case, we solve two equations:
\begin{gather*}
n \cdot 0.0124 = \left(\chi^2_{(K-1)(L-1)}\right)^{-1} (0.95) = \left(\chi^2_{6 \cdot 6}\right)^{-1} (0.95) = 50.99846 \\
n_{0.95} \approx 4113
\end{gather*}
By similar arguments we obtain sufficient number of observation for confidence level $0.99$:
\begin{gather*}
n \cdot 0.0124 = \left(\chi^2_{(K-1)(L-1)}\right)^{-1} (0.99) = \left(\chi^2_{6 \cdot 6}\right)^{-1} (0.99) = 58.61921 \\
n_{0.99} \approx 4727.356
\end{gather*}

Thus, we get demonstrative evidence why in the statistics textbooks the chi-squared is not recommended as a measure of association between
features. It is worth to mention, that the property described above is not the only one drawback of this statistic. Another one to mention is that $ \chi^2 $-test  depends on the number of intervals to split initial data  with and also of the width of such intervals. 

%</includetag>
